version: '3.8'

services:
  api:
    build:
      context: ./StockSpotter.API
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  clientapp:
    build:
      context: ./StockSpotter.ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
